# project config
MAIN    = main
OBJECTS = \
	usb_descriptors.o \
	main.o

APPLIB_OBJECTS = \
	$(APPLIB_PATH)/USB/usb_device.o \
	$(APPLIB_PATH)/USB/Generic\ Device\ Driver/usb_function_generic.o

APPLIB = libmchpapplib.o

include ../default.mk
